apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: localhost:5000/ecommerce-app:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9444

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-java-backend
spec:
  type: LoadBalancer
  ports:
    - port: 9444
      targetPort: 9444
      nodePort: 30000  # Elige un número de puerto válido
  selector:
    app: ecommerce-java-backend
