apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-javabackend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-user-binding
  namespace: ecommerce-javabackend
subjects:
- kind: ServiceAccount
  name: jenkins-user
  namespace: ecommerce-javabackend
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-user
  namespace: ecommerce-javabackend
